PROJECT_SOURCEFILES += cooja-radio-cb.c
all: gumbo_node

#APPS=servreg-hack
CONTIKI=../../../../contiki

#WITH_UIP6=1
#UIP_CONF_IPV6=1
#CFLAGS+= -DUIP_CONF_IPV6_RPL

include $(CONTIKI)/Makefile.include
